### ISSUE TITLE
Data type issues

### ISSUE THREAD

**Issue by yinyhang** [EvdokimovVladimir/bio-multifractal#1]
Hello author, I would like to ask for example in the table named Elnik_2009-2010, what do the numbers zero and decimal represent?![data](https://user-images.githubusercontent.com/127462743/226839925-b7d6c9fd-6f0c-49d4-a70a-e72a76aa7f48.jpg)

**Comment by EvdokimovVladimir** [comment]
Hello!
This is phytomass in kilograms, not the number of individuals. In botany, in most cases it is impossible to determine in the field where one individual is and where the other is.

This is mathematically incorrect. The method was developed for the number of individuals — an integer number.
But my supervisor decided to do it the way it's done.

**Comment by yinyhang** [comment]
Thank you very much for your answer. May I ask you some more questions?

**Comment by EvdokimovVladimir** [comment]
You are welcome
